<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\NotificationHandler;
use Illuminate\Contracts\Logging\Log;

class Ticket extends Model
{
    protected $fillable = [
        'tweet_id', 'premium', 'urgency', 'assigned_to', 'opened_by', 'customer_id'
    ];

    protected $table = 'tickets';


//    public static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//
//        static::saved(function ($ticket) {
//            Log::info('on saved');
//            dd('hello');
//            if ($ticket->isValid()) {
//                Log::info('valid');
//                $user = $ticket->with('assigned_to')->first();
//
//                NotificationHandler::makeNotification($user, $ticket);
//
//            }
//
//        });
//    }


    public function opened_by()
    {
        return $this->belongsTo('App\User');
    }

    public function assigned_to()
    {
        return $this->belongsTo('App\User');
    }

    public function invitations()
    {
        return $this->hasMany('App\Invitation');
    }

    public function users()
    {
        return $this->belongsToMany('App\User');
    }

    public function customer()
    {
        return $this->belongsTo('App\Customer');
    }


    public function scopeOfUserWithStatus($query, $userId, $status)
    {
        return $query->where('assigned_to', $userId)->where('status', $status);
    }


     public function get_status($id){
        if($id == 1){
            return 'in progress';
        }
        if($id == 2){
            return 'closed';
        }
        if($id == 0){
            return 'open';
        }
    }
    public function get_name($id)
    {
        
        $user = User::findOrFail($id);
        $name = $user->name;
        return $name;
       
        
    }
}
